#!/usr/bin/env bash

# Installs Nginx with the following configurations:

#+    Listens on port 80.

#+    Returns a page containing "Hello World!" when queried

#+     at the root with a curl GET request.

#+    Configures /redirect_me as a "301 Moved Permanently".

#+    Includes a custom 404 page containing "Ceci n'est pas une page".

#+    Contains a custom HTTP header named X-Served-By.

#+    The value of the HTTP header is the hostname of the running server.

# configurig web-01 to have an HTTP response header

sudo apt-get update
sudo apt-get install -y

echo "Hello world!" | sudo tee /var/www/html/index.html

# performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect-me https:\/\/github.com\/Ola-tek" permanent

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "cest n'est pass une page" | sudo tee /var/www/html/404.html

sudo sed -i "s/server_name _;/a add_header X-Served-By $HOSTNAME" /etc/nginx/sites-enabled/default

# Test for syntax errors
  sudo nginx -t

# Restart nginx
  sudo service nginx restart
