#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

range=0

while [ $range -lt 10 ]
do
	if [ $range -eq 3 ]
	then
		echo "bad luck"
	elif [ $range -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( range++ ))
done
