#!/usr/bin/env bash
#bash script that displays the time for 12 hours and 59 minutes
#displays hours from 1-12
#displys minutes from 0-59

hour=0

while [ $hour -le 12 ]

do

	echo "Hour: $hour"

	minute=1

	while [ $minute -le 59 ]

	do

		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))

done


