#!/usr/bin/env bash
#ssh client configuration

HOST *
  passwordAuthentication no
  IdentityFile ~/.ssh/school
  sendEnv LANG LC_*
  HashKnownHosts yes
  GSSAPIAuthentication yes
  GSSAPIDelegate Credentials no
